name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  DEPLOY_DIR: /home/ubuntu/prod/
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-44-201-244-211.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p $DEPLOY_DIR
            cd build
            mv * $DEPLOY_DIR
            pm2 restart my-app

