on:
  push:
    branches: main

env:
  DEPLOY_DIR: /home/ubuntu/prod/
  BACKUP_DIR: /home/ubuntu/backup/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: CI=false npm run build
    - name: Backup and Start Application
      run: |
        ssh -i ${{ secrets.AWS_SECRET_KEY }} ubuntu@3.92.216.148 '
          mkdir -p $DEPLOY_DIR
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          if [ -d "$DEPLOY_DIR/build" ]; then
            mv $DEPLOY_DIR/build $BACKUP_DIR/build_$TIMESTAMP
          fi
          if tmux has-session -t serve_session 2>/dev/null; then
            tmux kill-session -t serve_session
          fi
          cd $DEPLOY_DIR
          npm install serve
          tmux new-session -d -s serve_session './node_modules/.bin/serve -s .'
        '
