name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  DEPLOY_DIR: /home/ubuntu/prod/
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 44.201.244.211
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_KEY }}
          script: |
            ssh ubuntu@44.201.244.211 'mkdir -p $DEPLOY_DIR'
            scp -r build/* ubuntu@44.201.244.211:$DEPLOY_DIR

            # Restart your service (assuming using PM2)
            ssh ubuntu@44.201.244.211 'pm2 restart my-app'

