on:
  push:
    branches: main

env:
  DEPLOY_DIR: /home/ubuntu/prod/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: CI=false npm run build
    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY }}
        REMOTE_HOST: 3.92.216.148
        REMOTE_USER: ubuntu
        REMOTE_PORT: 22
        SOURCE: "build/"
        TARGET: $DEPLOY_DIR/build
    - name: Start Application
      uses: appleboy/ssh-action@v0.1.5
      with:
          host: 3.92.216.148
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_KEY }}
          script: |
            pwd
            cd prod/build
            pwd
            npm install serve
            tmux new-session -d -s serve_session './node_modules/.bin/serve -s .'

