name: CI/CD

on:
  push:
    branches:
      - main
env:
  SSH_USER: ubuntu
  SSH_HOST: 3.80.209.201
  DEPLOY_DIR: /home/ubuntu/prod
  BACKUP_DIR: /home/ubuntu/backup
  SERVE_PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Move previous build to backup and clean deploy directory
        run: ssh $SSH_USER@$SSH_HOST "mv $DEPLOY_DIR/build $BACKUP_DIR && rm -rf $DEPLOY_DIR/build"

      - name: Copy build artifacts to server
        run: scp -r build $SSH_USER@$SSH_HOST:$DEPLOY_DIR

      - name: Install serve and start application
        run: |
          ssh $SSH_USER@$SSH_HOST "
            cd $DEPLOY_DIR/build &&
            npm install serve &&
            tmux new-session -d -s serve_session 
            './node_modules/.bin/serve -s . -p $SERVE_PORT'
          "
